# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [17]:
import numpy as np
a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])
print(np.sqrt(a))
print(np.exp(a/2))
print(a + b)
print(a * b)
print(np.arange(0, 30, 0.5, dtype=float))
print(np.linspace(1, 2, 100))
first_line = np.linspace(10, 20, 6)
second_line = np.linspace(20, 10, 6)
array_2x6 = np.array([first_line, second_line])
print(array_2x6)
print(np.dot(a, b))
A = np.array([a, b])
print(matrice)
y = np.dot(A,b)
print(y)
D = np.diag(a)
print(D)

[1.09544512 2.32379001 2.44948974 1.26095202]
[ 1.8221188  14.87973172 20.08553692  2.214441  ]
[6.4  6.6  7.5  3.59]
[6.24 6.48 9.   3.18]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5]
[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636 1.37373737 1.38383838 1.39393939 1.4040404  1.41414141
 1.42424242 1.43434343 1.44444444 1.45454545 1.46464646 1.47474747
 1.48484848 1.4949

# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [44]:
import numpy as np
# creazione matrice A
A = np.full((3, 4), 2)
A[:,-1] = 3
print("Matrice A")
print(A)

# creazione matrice B
print("Matrice B")
matrix_diagonal = np.diag([2, 2, 2])
one_to_ten = np.arange(1, 11)
matrix_one_ten = np.tile(one_to_ten, (3, 1))
B = np.hstack((matrix_diagonal, matrix_one_ten))
print(B)

# creazione matrice C
C = np.zeros((5, 5))
np.fill_diagonal(C, 2)
np.fill_diagonal(C[1:], -1)
np.fill_diagonal(C[:, 1:], -1)
print("Matrice C")
print(C)

# creazione matrice D
print("Matrice D")
first_row = np.array([2, 2, 3, 3])
first_two_rows = np.tile(first_row, (2, 1))
zeros = np.zeros((4, 4))
zeros[2, 2] = 5
zeros[3, 3] = 5
D = np.vstack((first_two_rows, zeros))
print(D)

Matrice A
[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
Matrice B
[[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]]
Matrice C
[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
Matrice D
[[2. 2. 3. 3.]
 [2. 2. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [48]:
import numpy as np
def somma_dispari_ciclo_for(n):
    somma = 0
    i = 0
    num = 1
    while i < n:
        somma += num
        num += 2
        i+=1
    return somma

def somma_numpy(n):
    numeri_dispari = np.arange(1, 2*n, 2)
    return np.sum(numeri_dispari)
n = 6
print("somma dei primi ", n, "numeri dispari: ", somma_numpy(n))
print("somma dei primi ", n, "numeri dispari: ", somma_dispari_ciclo_for(n))

somma dei primi  6 numeri dispari:  36
somma dei primi  6 numeri dispari:  36


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$

In [50]:
def fib_ricorsivo(n):
    if n < 2:
        return n
    else:
        return fib_ricorsivo(n-1) + fib_ricorsivo(n-2)
def fib_iterativo(n):
    if n < 2:
        return n
    else:
        a, b = 0, 1
        for _ in range(2, n+1):
            a, b = b, a+b
        return b
n = 10
print("Fibonacci di", n, ":", fib_ricorsivo(n))
print("Fibonacci di", n, ":", fib_iterativo(n))

Fibonacci di 10 : 55
Fibonacci di 10 : 55
